title: Dave Brock
author: Dave Brock
email: daveabrock@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  A technical blog focusing on JavaScript and Microsoft technologies.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Dave Brock
  #tagline: Software Engineer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  disqus_shortname: daveabrock
  analytics_id: UA-83589168-1

  # generate social links in footer
  social_links:
    twitter: daveabrock
    github: daveabrock
    #linkedIn: in/daveabrock
    rss: feed
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
  - jekyll-feed
